export default {
    "aren't": ['are not'],
    "can't": ['cannot'],
    "couldn't": ['could not'],
    "could've": ['could have'],
    "didn't": ['did not'],
    "doesn't": ['does not'],
    "don't": ['do not'],
    "e'er": ['ever'],
    "hadn't": ['had not'],
    "hasn't": ['has not'],
    "haven't": ['have not'],
    "he'd": ['he had', 'he would'],
    "he'll": ['he will', 'he shall'],
    "he's": ['he is', 'he has'],
    "I'd": ['I had', 'I would'],
    "I'll": ['I will', 'I shall'],
    "I'm": ['I am'],
    "I've": ['I have'],
    "isn't": ['is not'],
    "it'd": ['it would'],
    "it'll": ['it shall', 'it will'],
    "it's": ['it is', 'it has'],
    "let's": ['let us'],
    "ma'am": ['madam'],
    "mightn't": ['might not'],
    "might've": ['might have'],
    "mustn't": ['must not'],
    "must've": ['must have'],
    "'n": ['and'],
    "needn't": ['need not'],
    "ne'er": ['never'],
    "o'er": ['over'],
    "ol'": ['old'],
    "oughtn't": ['ought not'],
    "shan't": ['shall not'],
    "she'd": ['she had', 'she would'],
    "she'll": ['she will', 'she shall'],
    "she's": ['she is', 'she has'],
    "shouldn't": ['should not'],
    "should've": ['should have'],
    "that'd": ['that would'],
    "that's": ['that is', 'that has'],
    "there'd": ['there had', 'there would'],
    "there'll": ['there shall', 'there will'],
    "there's": ['there has', 'there is'],
    "they'd": ['they had', 'they would'],
    "they'll": ['they will', 'they shall'],
    "they're": ['they are'],
    "they've": ['they have'],
    "'twas": ['it was'],
    "wasn't": ['was not'],
    "we'd": ['we had', 'we would'],
    "we'll": ['we will'],
    "we're": ['we are'],
    "we've": ['we have'],
    "weren't": ['were not'],
    "what'll": ['what will', 'what shall'],
    "what're": ['what are'],
    "what's": ['what is', 'what has', 'what does'],
    "what've": ['what have'],
    "where'd": ['where did'],
    "where's": ['where is', 'where has'],
    "who'd": ['who had', 'who would'],
    "who'll": ['who will', 'who shall'],
    "who's": ['who is', 'who has'],
    "who've": ['who have'],
    "why'd": ['why did'],
    "won't": ['will not'],
    "wouldn't": ['would not'],
    "would've": ['would have'],
    "you'd": ['you had', 'you would'],
    "you'll": ['you will', 'you shall'],
    "you're": ['you are'],
    "you've": ['you have'],
};